server:
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    cache: false
    suffix:  .html
    mode: HTML

#使用了mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.zfsoft.certificate.pojo
  configuration:
    #是否开启自动驼峰命名规则映射
    map-underscore-to-camel-case: true
    cache-enabled: false

#是否开启swagger文档
# http://localhost:8080/swagger-ui.html
# http://localhost:8080/doc.html
swagger:
  enable: false


logging:
  config: classpath:logback-spring.xml

# Sa-Token-Quick-Login 配置
#sa:
#  name: admin
#  pwd: 123456
#  auto: false
#  auth: true
#  title: 证照工具登陆
#  copr: true
